# Generated by Django 5.2.3 on 2025-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(blank=True, to='app.question'),
        ),
    ]
